/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerated sidebar from filesystem - new markdown files will appear automatically
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the docs folder
    },
  ],
};

export default sidebars;
